version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    entrypoint: bundle exec jekyll serve --verbose --host 0.0.0.0
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4040:4040'
    entrypoint: bundle exec jekyll build --verbose && npx serve -l 4040 _site
